### ISSUE TITLE
Not Phone Friendly - Feature Request

### ISSUE THREAD

**Issue by taylor-russon** [info442-su23/g-team#54] opened 2023-08-09 00:39 UTC
I am using my iPhone 13 iOS Version 16.6 on Safari and nothing seems to be scaled for this screen size. The navbar is cut off and the pages move around when I try to scroll making it difficult to navigate the page.

![IMG_4143](https://github.com/info442-su23/g-team/assets/91644521/889c7129-070c-4493-9680-9e7eee08c327)

**Comment by jasmpa-1777547** [comment] 2023-08-11 00:41
Duplicate of another post

**Closed by jasmpa-1777547** 2023-08-11 00:41 UTC
Labels: duplicate
